version: '3'
services:
  postgres:
    image: postgres:13
    container_name: awx-postgres
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
    volumes:
      - awx_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - awx_network

  redis:
    image: redis:7
    container_name: awx-redis
    restart: unless-stopped
    networks:
      - awx_network

  awx-web:
    image: ghcr.io/ansible/awx:latest
    container_name: awx-web
    depends_on:
      - postgres
      - redis
    environment:
      AWX_ADMIN_USER: admin
      AWX_ADMIN_PASSWORD: your_strong_password  # Замените на свой!
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - awx_projects:/var/lib/awx/projects
    ports:
      - "8052:8052"  # AWX Web UI (замените на свободный, если занят)
      - "8013:8013"  # AWX Receiver (опционально)
    restart: unless-stopped
    networks:
      - awx_network

  awx-task:
    image: ghcr.io/ansible/awx:latest
    container_name: awx-task
    depends_on:
      - postgres
      - redis
    environment:
      AWX_ADMIN_USER: admin
      AWX_ADMIN_PASSWORD: your_strong_password  # Должен совпадать с awx-web!
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - awx_projects:/var/lib/awx/projects
    restart: unless-stopped
    networks:
      - awx_network

volumes:
  awx_postgres_data:
  awx_projects:

networks:
  awx_network:
    driver: bridge
