version: '3.8'
services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    environment:
      - SEMAPHORE_DB_HOST=db
      - SEMAPHORE_DB_PORT=5432
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=your_db_password  # Замените!
      - SEMAPHORE_DB_NAME=semaphore
      - SEMAPHORE_DB_DIALECT=postgres
      - SEMAPHORE_ADMIN_PASSWORD=admin123    # Замените!
      - SEMAPHORE_ADMIN_NAME=Admin
      - SEMAPHORE_ADMIN_EMAIL=admin@example.com
      - SEMAPHORE_PORT=5000                  # Меняем порт на 5000
    volumes:
      - semaphore_data:/etc/semaphore
      - /path/to/ansible:/etc/ansible       # Монтируем каталог с playbooks
    ports:
      - "5000:5000"                         # Пробрасываем порт 5000
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: semaphore_db
    environment:
      - POSTGRES_USER=semaphore
      - POSTGRES_PASSWORD=your_db_password   # Должен совпадать с SEMAPHORE_DB_PASS
      - POSTGRES_DB=semaphore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  semaphore_data:
  postgres_data:
