---
- name: Установить и настроить веб-сервер
  hosts: all
  become: yes

  tasks:
    - name: Установить Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Запустить и включить службу Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Скопировать файл конфигурации Nginx
    ansible.builtin.git:
    repo: "https://github.com/Airn123/ansible.git
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify:
        - Перезагрузить Nginx

  handlers:
    - name: Перезагрузить Nginx
      service:
        name: nginx
        state: reloaded
