---
- name: Deploy Nginx from GitHub repository
  hosts: all
  become: yes
  vars:
    github_user: "Airn123"
    github_repo: "ansible"
    github_branch: "main"  # или ваша ветка

  tasks:
    # 1. Установка зависимостей
    - name: Install required packages
      apt:
        name: ["nginx", "git"]
        state: present
        update_cache: yes

    # 2. Клонирование репозитория с конфигами
    - name: Clone configuration repository
      ansible.builtin.git:
        repo: "https://github.com/{{ github_user }}/{{ github_repo }}.git"
        dest: /tmp/nginx-config
        version: "{{ github_branch }}"
        force: yes

    # 3. Копирование основных конфигов
    - name: Deploy main nginx config
      ansible.builtin.template:
        src: "/tmp/nginx-config/templates/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    # 4. Копирование конфигов сайтов (если есть)
    - name: Deploy site configurations
      ansible.builtin.copy:
        src: "/tmp/nginx-config/files/sites-available/"
        dest: "/etc/nginx/sites-available"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      when: "'sites-available' in lookup('fileglob', '/tmp/nginx-config/files/sites-available/*')"
      notify: reload nginx

    # 5. Активация сайтов
    - name: Enable sites
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ item }}"
        dest: "/etc/nginx/sites-enabled/{{ item }}"
        state: link
      loop: "{{ lookup('fileglob', '/tmp/nginx-config/files/sites-available/*').split(',') | map('basename') | list }}"
      when: "'sites-available' in lookup('fileglob', '/tmp/nginx-config/files/sites-available/*')"
      notify: reload nginx

    # 6. Развертывание статики (если есть)
    - name: Deploy static content
      ansible.builtin.copy:
        src: "/tmp/nginx-config/files/html/"
        dest: "/var/www/html"
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: yes
      when: "'html' in lookup('fileglob', '/tmp/nginx-config/files/html/*')"

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
