---
- name: Deploy Nginx from GitHub repository
  hosts: all
  become: yes
  vars:
    github_user: "Airn123"
    github_repo: "ansible"
    github_branch: "main"
    temp_dir: "/tmp/nginx-config-{{ ansible_date_time.epoch }}"

  tasks:
    # 1. Установка зависимостей
    - name: Install required packages
      apt:
        name: ["nginx", "git"]
        state: present
        update_cache: yes

    # 2. Создание временной директории
    - name: Create temporary directory
      file:
        path: "{{ temp_dir }}"
        state: directory
        mode: '0755'

    # 3. Клонирование репозитория
    - name: Clone configuration repository
      ansible.builtin.git:
        repo: "https://github.com/{{ github_user }}/{{ github_repo }}.git"
        dest: "{{ temp_dir }}"
        version: "{{ github_branch }}"
        force: yes

    # 4. Проверка существования файлов
    - name: Check if template exists
      stat:
        path: "{{ temp_dir }}/templates/nginx.conf.j2"
      register: template_stat

    # 5. Развертывание конфигурации
    - name: Deploy nginx config
      ansible.builtin.template:
        src: "{{ temp_dir }}/templates/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
        owner: root
        group: root
        mode: '0644'
      when: template_stat.stat.exists
      notify: restart nginx

    # 6. Очистка временных файлов
    - name: Clean up temporary files
      file:
        path: "{{ temp_dir }}"
        state: absent
      when: cleanup|default(true)

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
